// flow-typed signature: 9fa170a7b4441d84616b206972d58a72
// flow-typed version: <<STUB>>/tone_v^0.12.44/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tone' {
  declare export class AudioNode {
    dispose(): this;
    toMaster(): this;
  }
  declare export class Instrument extends AudioNode {}

  declare export class Monophonic extends Instrument {}
  declare export class Synth extends Monophonic {}
  declare export class DuoSynth extends Monophonic {}
  declare export class FMSynth extends Monophonic {}

  declare export class PolySynth extends Instrument {
    constructor(polyphony?: number, voice?: Class<Monophonic>): void;
    triggerAttack(notes: string | string[]): this;
    triggerRelease(notes: string | string[]): this;
    set(prop: string, value: mixed): this;
    set(props: { [string]: mixed }): this;
  }

  declare export default {|
    +AudioNode: AudioNode,
    +Instrument: Instrument,
    +Monophonic: Monophonic,
    +Synth: Synth,
    +DuoSynth: DuoSynth,
    +FMSynth: FMSynth,
    +PolySynth: PolySynth,
  |};
}
